#!/usr/bin/env python3
# Copyright(c) MobilityDB Contributors
# Licensed under the PostgreSQL License (see LICENSE.txt).
"""Generate the Arrow C Data Interface round-trip SQL registrations.

The Arrow export round-trips a CURATED set of types per category (the C raises
MEOS_ERR_FEATURE_NOT_SUPPORTED otherwise). Hand-listing arrowRoundtrip(<type>)
across ~10 family SQL files made every entry a special-case with no single PR
home -- the th3index registration in particular was an orphan between the h3
type PR (no Arrow) and the Arrow PR (no h3). This tool emits one generated
<NNN>_arrow_roundtrip.in.sql per family directory from the single curated
catalog below, reusing each category's generic backing C symbol. Mirrors
tools/portable_aliases/generate.py; auto-included by append_arrow_roundtrip().

To add Arrow support for a new type: implement its leaf in temporal_arrow.c and
add it to CATALOG here -- the SQL registration is then generated, never hand-written.

Usage: python3 tools/arrow_roundtrip/generate.py [--sqldir DIR] [--check]
"""
import argparse, os, sys

SYMBOL = {'set':'Set_arrow_roundtrip','span':'Span_arrow_roundtrip',
    'spanset':'Spanset_arrow_roundtrip','tbox':'Tbox_arrow_roundtrip',
    'stbox':'Stbox_arrow_roundtrip','temporal':'Temporal_arrow_roundtrip'}

# Single curated source of Arrow-supported types: family dir -> NNN -> [(type,category)]
# Validated against the per-category support in meos/src/temporal/temporal_arrow.c.
CATALOG = {
  ('temporal','049'): [
    ('intset','set'),('bigintset','set'),('floatset','set'),('textset','set'),
    ('dateset','set'),('tstzset','set'),
    ('intspan','span'),('bigintspan','span'),('floatspan','span'),('datespan','span'),('tstzspan','span'),
    ('intspanset','spanset'),('bigintspanset','spanset'),('floatspanset','spanset'),
    ('datespanset','spanset'),('tstzspanset','spanset'),
    ('tbox','tbox'),
    ('tbool','temporal'),('tint','temporal'),('tfloat','temporal'),('ttext','temporal')],
  ('geo','078'): [
    ('geomset','set'),('geogset','set'),('stbox','stbox'),
    ('tgeompoint','temporal'),('tgeogpoint','temporal'),
    ('tgeometry','temporal'),('tgeography','temporal')],
  ('cbuffer','298'): [('tcbuffer','temporal')],
  ('h3','297'):      [('th3index','temporal')],
  ('pose','114'):    [('tpose','temporal')],
  ('rgeo','198'):    [('trgeometry','temporal')],
}
HEADER = '''/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Universite libre de Bruxelles and MobilityDB
 * contributors
 *
 *****************************************************************************/

/**
 * @file
 * @brief Arrow C Data Interface round-trip registrations ({fam} family).
 *
 * GENERATED by tools/arrow_roundtrip/generate.py -- DO NOT EDIT.
 * Each arrowRoundtrip(<type>) reuses the category's generic backing C symbol.
 */

'''
TMPL = ("CREATE FUNCTION arrowRoundtrip({t})\n  RETURNS {t}\n"
        "  AS 'MODULE_PATHNAME', '{sym}'\n  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;\n\n")

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--sqldir',default='mobilitydb/sql')
    ap.add_argument('--check',action='store_true'); a=ap.parse_args(); rc=0
    for (fam,nnn),types in CATALOG.items():
        body=HEADER.format(fam=fam)
        for t,cat in types: body+=TMPL.format(t=t,sym=SYMBOL[cat])
        out=os.path.join(a.sqldir,fam,f"{nnn}_arrow_roundtrip.in.sql")
        if a.check:
            cur=open(out).read() if os.path.exists(out) else ''
            if cur!=body: print(f"DRIFT: {out}"); rc=1
        else: open(out,'w').write(body); print(f"wrote {out} ({len(types)})")
    return rc
if __name__=='__main__': sys.exit(main())
