/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Universite libre de Bruxelles and MobilityDB
 * contributors
 *
 *****************************************************************************/

/**
 * @file
 * @brief Arrow C Data Interface round-trip registrations (geo family).
 *
 * GENERATED by tools/arrow_roundtrip/generate.py -- DO NOT EDIT.
 * Each arrowRoundtrip(<type>) reuses the category's generic backing C symbol.
 */

CREATE FUNCTION arrowRoundtrip(geomset)
  RETURNS geomset
  AS 'MODULE_PATHNAME', 'Set_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(geogset)
  RETURNS geogset
  AS 'MODULE_PATHNAME', 'Set_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(stbox)
  RETURNS stbox
  AS 'MODULE_PATHNAME', 'Stbox_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(tgeompoint)
  RETURNS tgeompoint
  AS 'MODULE_PATHNAME', 'Temporal_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(tgeogpoint)
  RETURNS tgeogpoint
  AS 'MODULE_PATHNAME', 'Temporal_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(tgeometry)
  RETURNS tgeometry
  AS 'MODULE_PATHNAME', 'Temporal_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(tgeography)
  RETURNS tgeography
  AS 'MODULE_PATHNAME', 'Temporal_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

