/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Universite libre de Bruxelles and MobilityDB
 * contributors
 *
 *****************************************************************************/

/**
 * @file
 * @brief Arrow C Data Interface round-trip registrations (rgeo family).
 *
 * GENERATED by tools/arrow_roundtrip/generate.py -- DO NOT EDIT.
 * Each arrowRoundtrip(<type>) reuses the category's generic backing C symbol.
 */

CREATE FUNCTION arrowRoundtrip(trgeometry)
  RETURNS trgeometry
  AS 'MODULE_PATHNAME', 'Temporal_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

