#!/usr/bin/env bash
#
# Build every MEOS smoke-test in this directory, run each under
# valgrind, and exit non-zero if any suite crashes or leaks.
#
# Usage:
#   meos/test/run_smoketests.sh                # use system MEOS in /usr/local
#   MEOS_BUILD_DIR=./build ./run_smoketests.sh # use a local MEOS build
#
# The smoke-test C files are auto-generated by gen_smoketest.py from the
# corresponding meos_*.h public headers. Each test runs every public
# function once with canned inputs; a clean valgrind run is the
# project's only floor against memory leaks that the PG infrastructure
# would otherwise hide.
#
# tgeometry_smoketest uses --leak-check=summary (not --leak-check=full)
# because the PROJ/SQLite3 SRS database lookups generate thousands of
# "possibly lost" records that exhaust valgrind's internal accounting.
# MEOS leaks in the tgeometry suite are caught by other means (ASan CI).

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
MEOS_BUILD_DIR="${MEOS_BUILD_DIR:-/usr/local/lib}"
MEOS_INCLUDE_DIR="${MEOS_INCLUDE_DIR:-/usr/local/include}"

# Core, always-built suite (meos_geo.h). Optional families add themselves via a
# meos/test/smoke/<family>.json sidecar, discovered below — never listed here.
SUITES=(
  tgeometry_smoketest
)

# Self-contained family suites: a family drops meos/test/smoke/<family>.json and
# is DISCOVERED here (never centrally listed) — mirroring append_portable_aliases'
# file(GLOB ...). Each suite name comes from the sidecar's "out" field, and its
# valgrind leak-check mode from the optional "leak_check" field (default "full";
# spatial families set "summary"). The per-suite loop below skips any suite whose
# .c was not generated (its feature / header absent on this build), so a
# discovered family is safe on a partial build.
#
# The core geometry suite uses --leak-check=summary: a full check OOMs valgrind
# on the PROJ/SQLite3 SRS allocations, and the geometry-backed bbox paths report
# leaks the test cannot free; MEOS leaks are caught by ASan CI.
declare -A LEAK_MODE=( [tgeometry_smoketest]=summary )
if command -v python3 >/dev/null 2>&1; then
  for _sc in "$HERE"/smoke/*.json; do
    [ -e "$_sc" ] || continue
    _name="$(python3 -c "import json,sys;print(json.load(open(sys.argv[1]))['out'][:-2])" "$_sc")"
    SUITES+=("$_name")
    LEAK_MODE["$_name"]="$(python3 -c "import json,sys;print(json.load(open(sys.argv[1])).get('leak_check','full'))" "$_sc")"
  done
fi

mkdir -p "$HERE/build"

fail=0
for suite in "${SUITES[@]}"; do
  src="$HERE/$suite.c"
  bin="$HERE/build/$suite"
  if [ ! -f "$src" ]; then
    echo "[skip] $suite: $src missing"
    continue
  fi
  echo "[build] $suite"
  gcc -Wall -g -I"$MEOS_INCLUDE_DIR" -o "$bin" "$src" \
    -L"$MEOS_BUILD_DIR" -lmeos -lm
  echo "[run]   $suite"
  vg_leak="--leak-check=${LEAK_MODE[$suite]:-full}"
  if ! LD_LIBRARY_PATH="$MEOS_BUILD_DIR" valgrind \
        $vg_leak --error-exitcode=1 --quiet \
        --suppressions="$HERE/meos_smoketest.supp" \
        "$bin" >"$bin.out" 2>"$bin.err"; then
    echo "[FAIL]  $suite — see $bin.out / $bin.err"
    fail=1
  else
    lines=$(wc -l < "$bin.out")
    warns=$(wc -l < "$bin.err")
    echo "[ok]    $suite — $lines results, $warns validation warns"
  fi
done

if [ "$fail" -ne 0 ]; then
  echo
  echo "One or more smoke suites failed. Inspect the .out / .err files"
  echo "in meos/test/build/ for the call site of the leak or crash."
  exit 1
fi

echo
echo "All smoke suites passed valgrind."
