/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2026, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/**
 * @file
 * @brief MEOS unit test for the trgeometry public API.
 *
 * Auto-generated by meos/test/gen_trgeometry_test.py — do not edit by hand.
 *
 * Each public symbol exported by meos/include/meos_rgeo.h gets one
 * smoke-test call site here. The arguments are drawn from a shared
 * common-inputs block. The test confirms every public symbol is linkable,
 * callable without crashing, and produces a result of the expected
 * non-null/null shape. Pointer results are freed.
 *
 * The test is designed to be valgrind-clean — a successful run under
 *
 *     valgrind --leak-check=full --error-exitcode=1 ./trgeometry_test
 *
 * exits 0 with no leaks reported.
 *
 * Build:
 *   gcc -Wall -g -I/usr/local/include -o trgeometry_test \
 *       trgeometry_test.c -L/usr/local/lib -lmeos -lm
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <meos.h>
#include <meos_geo.h>
#include <meos_pose.h>
#include <meos_rgeo.h>

/* Datum is opaque from the public API; expose just enough to satisfy
 * any signature that takes one. The kernel only inspects the value
 * through the matching DatumGet helper. */
#ifndef DatumDefined
typedef uintptr_t Datum;
#define DatumDefined 1
#endif

/* trgeometry_restrict_value is an internal kernel entry (declared in the
 * internal rgeo/trgeo.h, not the public meos_rgeo.h) because it takes a raw
 * Datum; the public restrict API is the Set-based trgeometry_restrict_values.
 * This smoke suite exercises the kernel entry directly with a packed Datum, so
 * forward-declare it here rather than pull in the internal header. */
extern Temporal *trgeometry_restrict_value(const Temporal *temp, Datum value,
  bool atfunc);

/* Non-fatal error handler: lets the smoke suite continue past a
 * VALIDATE_* failure or an unsupported-feature error. We just print and
 * return — the calling function must then handle the NULL/sentinel
 * itself. */
static void
test_error_handler(int level, int code, const char *msg)
{
  (void) level; (void) code;
  fprintf(stderr, "[meos warn] %s\n", msg);
}

int
main(void)
{
  meos_initialize();
  meos_initialize_timezone("UTC");
  meos_initialize_error_handler(test_error_handler);

  /* ----------------------------------------------------------
   * Common inputs reused across the auto-generated call sites.
   * --------------------------------------------------------*/
  TimestampTz tstz1 = pg_timestamptz_in("2001-01-02", -1);
  Span *tstzspan1 = tstzspan_in("[2001-01-01, 2001-01-04]");
  Set *tstzset1 = tstzset_in("{2001-01-02, 2001-01-03}");
  SpanSet *tstzspanset1 = tstzspanset_in("{[2001-01-01, 2001-01-02], [2001-01-03, 2001-01-04]}");
  Interval *interv1 = NULL;
  GSERIALIZED *geom1 = geom_in("Polygon((0 0,1 0,1 1,0 1,0 0))", -1);
  GSERIALIZED *geom_out_param = NULL;
  Pose *pose1 = pose_in("Pose(Point(0 0), 0.0)");
  STBox *stbox1 = stbox_in("STBOX X((0, 0), (10, 10))");
  /* trgeometry_restrict_value's Datum carries a GSERIALIZED — pack via
   * PointerGetDatum equivalent (cast). The function never dereferences
   * the pointer it doesn't recognise, so a bogus value still smoke-tests. */
  Datum geom1_datum = (Datum) geom1;

  TInstant *trgeometry_inst1 = trgeoinst_make(geom1, pose1, tstz1);
  TInstant *trgeometry_inst2 = trgeoinst_make(geom1, pose1,
    pg_timestamptz_in("2001-01-03", -1));
  Temporal *trgeometry_seq1 = (Temporal *) trgeometry_inst1;
  trgeometry_seq1 = trgeometry_append_tinstant(trgeometry_seq1, trgeometry_inst2,
    LINEAR, 0.0, NULL, false);
  /* The append above promoted the TINSTANT to a TSEQUENCE. */
  TSequence    *trgeometry_tseq1    = (TSequence *) trgeometry_seq1;
  TSequenceSet *trgeometry_tseqset1 = NULL;  /* no public string parser */

  Temporal *tpoint1 = trgeometry_to_tpoint(trgeometry_seq1);
  Temporal *tpose1 = trgeometry_to_tpose(trgeometry_seq1);

  int n_out = 0;

  printf("****************************************************************\n");
  printf("* trgeometry MEOS smoke test                                  *\n");
  printf("****************************************************************\n");

  { char *r = trgeometry_out(trgeometry_seq1);
    printf("trgeometry_out: %s\n", r ? r : "NULL");
    if (r) free(r); }
  { TInstant * r = trgeoinst_make(geom1, pose1, tstz1);
    printf("trgeoinst_make: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = geo_tpose_to_trgeometry(geom1, tpose1);
    printf("geo_tpose_to_trgeometry: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeometry_to_tpose(trgeometry_seq1);
    printf("trgeometry_to_tpose: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeometry_to_tpoint(trgeometry_seq1);
    printf("trgeometry_to_tpoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * r = trgeometry_end_instant(trgeometry_seq1);
    printf("trgeometry_end_instant: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TSequence * r = trgeometry_end_sequence(trgeometry_seq1);
    printf("trgeometry_end_sequence: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = trgeometry_end_value(trgeometry_seq1);
    printf("trgeometry_end_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = trgeometry_geom(trgeometry_seq1);
    printf("trgeometry_geom: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * r = trgeometry_instant_n(trgeometry_seq1, 1);
    printf("trgeometry_instant_n: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * * r = trgeometry_instants(trgeometry_seq1, &n_out);
    printf("trgeometry_instants: %s\n", r ? "OK" : "NULL");
    if (r) { for (int i = 0; i < n_out; i++) free(r[i]); free(r); } }
  { Set * r = trgeometry_points(trgeometry_seq1);
    printf("trgeometry_points: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeometry_rotation(trgeometry_seq1);
    printf("trgeometry_rotation: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TSequence * * r = trgeometry_segments(trgeometry_seq1, &n_out);
    printf("trgeometry_segments: %s\n", r ? "OK" : "NULL");
    if (r) { for (int i = 0; i < n_out; i++) free(r[i]); free(r); } }
  { TSequence * r = trgeometry_sequence_n(trgeometry_seq1, 1);
    printf("trgeometry_sequence_n: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TSequence * * r = trgeometry_sequences(trgeometry_seq1, &n_out);
    printf("trgeometry_sequences: %s\n", r ? "OK" : "NULL");
    if (r) { for (int i = 0; i < n_out; i++) free(r[i]); free(r); } }
  { TInstant * r = trgeometry_start_instant(trgeometry_seq1);
    printf("trgeometry_start_instant: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TSequence * r = trgeometry_start_sequence(trgeometry_seq1);
    printf("trgeometry_start_sequence: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = trgeometry_start_value(trgeometry_seq1);
    printf("trgeometry_start_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  /* SKIP trgeometry_value_n: out-param GSERIALIZED ** is exercised manually below */
  /* SKIP trgeometry_traversed_area: pending union-of-swept-polygons implementation */
  { Temporal * r = trgeometry_append_tinstant(trgeometry_seq1, trgeometry_inst1, LINEAR, 1.0, interv1, true);
    printf("trgeometry_append_tinstant: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeometry_append_tsequence(trgeometry_seq1, trgeometry_tseq1, true);
    printf("trgeometry_append_tsequence: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeometry_delete_timestamptz(trgeometry_seq1, tstz1, true);
    printf("trgeometry_delete_timestamptz: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeometry_delete_tstzset(trgeometry_seq1, tstzset1, true);
    printf("trgeometry_delete_tstzset: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeometry_delete_tstzspan(trgeometry_seq1, tstzspan1, true);
    printf("trgeometry_delete_tstzspan: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeometry_delete_tstzspanset(trgeometry_seq1, tstzspanset1, true);
    printf("trgeometry_delete_tstzspanset: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeometry_round(trgeometry_seq1, 1);
    printf("trgeometry_round: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeometry_set_interp(trgeometry_seq1, LINEAR);
    printf("trgeometry_set_interp: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * r = trgeometry_to_tinstant(trgeometry_seq1);
    printf("trgeometry_to_tinstant: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeometry_after_timestamptz(trgeometry_seq1, tstz1, true);
    printf("trgeometry_after_timestamptz: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeometry_before_timestamptz(trgeometry_seq1, tstz1, true);
    printf("trgeometry_before_timestamptz: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeometry_restrict_value(trgeometry_seq1, geom1_datum, true);
    printf("trgeometry_restrict_value: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeometry_restrict_values(trgeometry_seq1, tstzset1, true);
    printf("trgeometry_restrict_values: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeometry_restrict_timestamptz(trgeometry_seq1, tstz1, true);
    printf("trgeometry_restrict_timestamptz: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeometry_restrict_tstzset(trgeometry_seq1, tstzset1, true);
    printf("trgeometry_restrict_tstzset: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeometry_restrict_tstzspan(trgeometry_seq1, tstzspan1, true);
    printf("trgeometry_restrict_tstzspan: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = trgeometry_restrict_tstzspanset(trgeometry_seq1, tstzspanset1, true);
    printf("trgeometry_restrict_tstzspanset: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdistance_trgeometry_geo(trgeometry_seq1, geom1);
    printf("tdistance_trgeometry_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdistance_trgeometry_tpoint(trgeometry_seq1, tpoint1);
    printf("tdistance_trgeometry_tpoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tdistance_trgeometry_trgeometry(trgeometry_seq1, trgeometry_seq1);
    printf("tdistance_trgeometry_trgeometry: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { double r = nad_stbox_trgeometry(stbox1, trgeometry_seq1);
    printf("nad_stbox_trgeometry: %.6f\n", r); }
  { double r = nad_trgeometry_geo(trgeometry_seq1, geom1);
    printf("nad_trgeometry_geo: %.6f\n", r); }
  { double r = nad_trgeometry_stbox(trgeometry_seq1, stbox1);
    printf("nad_trgeometry_stbox: %.6f\n", r); }
  { double r = nad_trgeometry_tpoint(trgeometry_seq1, tpoint1);
    printf("nad_trgeometry_tpoint: %.6f\n", r); }
  { double r = nad_trgeometry_trgeometry(trgeometry_seq1, trgeometry_seq1);
    printf("nad_trgeometry_trgeometry: %.6f\n", r); }
  { TInstant * r = nai_trgeometry_geo(trgeometry_seq1, geom1);
    printf("nai_trgeometry_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * r = nai_trgeometry_tpoint(trgeometry_seq1, tpoint1);
    printf("nai_trgeometry_tpoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { TInstant * r = nai_trgeometry_trgeometry(trgeometry_seq1, trgeometry_seq1);
    printf("nai_trgeometry_trgeometry: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = shortestline_trgeometry_geo(trgeometry_seq1, geom1);
    printf("shortestline_trgeometry_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = shortestline_trgeometry_tpoint(trgeometry_seq1, tpoint1);
    printf("shortestline_trgeometry_tpoint: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { GSERIALIZED * r = shortestline_trgeometry_trgeometry(trgeometry_seq1, trgeometry_seq1);
    printf("shortestline_trgeometry_trgeometry: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { int r = always_eq_geo_trgeometry(geom1, trgeometry_seq1);
    printf("always_eq_geo_trgeometry: %d\n", r); }
  { int r = always_eq_trgeometry_geo(trgeometry_seq1, geom1);
    printf("always_eq_trgeometry_geo: %d\n", r); }
  { int r = always_eq_trgeometry_trgeometry(trgeometry_seq1, trgeometry_seq1);
    printf("always_eq_trgeometry_trgeometry: %d\n", r); }
  { int r = always_ne_geo_trgeometry(geom1, trgeometry_seq1);
    printf("always_ne_geo_trgeometry: %d\n", r); }
  { int r = always_ne_trgeometry_geo(trgeometry_seq1, geom1);
    printf("always_ne_trgeometry_geo: %d\n", r); }
  { int r = always_ne_trgeometry_trgeometry(trgeometry_seq1, trgeometry_seq1);
    printf("always_ne_trgeometry_trgeometry: %d\n", r); }
  { int r = ever_eq_geo_trgeometry(geom1, trgeometry_seq1);
    printf("ever_eq_geo_trgeometry: %d\n", r); }
  { int r = ever_eq_trgeometry_geo(trgeometry_seq1, geom1);
    printf("ever_eq_trgeometry_geo: %d\n", r); }
  { int r = ever_eq_trgeometry_trgeometry(trgeometry_seq1, trgeometry_seq1);
    printf("ever_eq_trgeometry_trgeometry: %d\n", r); }
  { int r = ever_ne_geo_trgeometry(geom1, trgeometry_seq1);
    printf("ever_ne_geo_trgeometry: %d\n", r); }
  { int r = ever_ne_trgeometry_geo(trgeometry_seq1, geom1);
    printf("ever_ne_trgeometry_geo: %d\n", r); }
  { int r = ever_ne_trgeometry_trgeometry(trgeometry_seq1, trgeometry_seq1);
    printf("ever_ne_trgeometry_trgeometry: %d\n", r); }
  { Temporal * r = teq_geo_trgeometry(geom1, trgeometry_seq1);
    printf("teq_geo_trgeometry: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = teq_trgeometry_geo(trgeometry_seq1, geom1);
    printf("teq_trgeometry_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tne_geo_trgeometry(geom1, trgeometry_seq1);
    printf("tne_geo_trgeometry: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }
  { Temporal * r = tne_trgeometry_geo(trgeometry_seq1, geom1);
    printf("tne_trgeometry_geo: %s\n", r ? "OK" : "NULL");
    if (r) free(r); }

  /* Manually exercise trgeometry_value_n (out-param GSERIALIZED **). */
  {
    GSERIALIZED *out_geom = NULL;
    bool ok = trgeometry_value_n(trgeometry_seq1, 1, &out_geom);
    printf("trgeometry_value_n: ok=%d ptr=%s\n", (int) ok, out_geom ? "OK" : "NULL");
    if (out_geom) free(out_geom);
  }

  /* Cleanup. */
  free(trgeometry_inst1);
  free(trgeometry_inst2);
  if (trgeometry_seq1) free(trgeometry_seq1);
  if (tpoint1) free(tpoint1);
  if (tpose1) free(tpose1);
  free(stbox1);
  free(pose1);
  free(geom1);
  free(tstzspanset1);
  free(tstzset1);
  free(tstzspan1);

  meos_finalize();
  return 0;
}
