/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2026, Universite libre de Bruxelles and MobilityDB
 * contributors
 *
 *****************************************************************************/

/**
 * @file
 * @brief Arrow C Data Interface round-trip registrations (temporal family).
 *
 * GENERATED by tools/arrow_roundtrip/generate.py -- DO NOT EDIT.
 * Each arrowRoundtrip(<type>) reuses the category's generic backing C symbol.
 */

CREATE FUNCTION arrowRoundtrip(intset)
  RETURNS intset
  AS 'MODULE_PATHNAME', 'Set_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(bigintset)
  RETURNS bigintset
  AS 'MODULE_PATHNAME', 'Set_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(floatset)
  RETURNS floatset
  AS 'MODULE_PATHNAME', 'Set_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(textset)
  RETURNS textset
  AS 'MODULE_PATHNAME', 'Set_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(dateset)
  RETURNS dateset
  AS 'MODULE_PATHNAME', 'Set_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(tstzset)
  RETURNS tstzset
  AS 'MODULE_PATHNAME', 'Set_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(intspan)
  RETURNS intspan
  AS 'MODULE_PATHNAME', 'Span_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(bigintspan)
  RETURNS bigintspan
  AS 'MODULE_PATHNAME', 'Span_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(floatspan)
  RETURNS floatspan
  AS 'MODULE_PATHNAME', 'Span_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(datespan)
  RETURNS datespan
  AS 'MODULE_PATHNAME', 'Span_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(tstzspan)
  RETURNS tstzspan
  AS 'MODULE_PATHNAME', 'Span_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(intspanset)
  RETURNS intspanset
  AS 'MODULE_PATHNAME', 'Spanset_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(bigintspanset)
  RETURNS bigintspanset
  AS 'MODULE_PATHNAME', 'Spanset_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(floatspanset)
  RETURNS floatspanset
  AS 'MODULE_PATHNAME', 'Spanset_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(datespanset)
  RETURNS datespanset
  AS 'MODULE_PATHNAME', 'Spanset_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(tstzspanset)
  RETURNS tstzspanset
  AS 'MODULE_PATHNAME', 'Spanset_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(tbox)
  RETURNS tbox
  AS 'MODULE_PATHNAME', 'Tbox_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(tbool)
  RETURNS tbool
  AS 'MODULE_PATHNAME', 'Temporal_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(tint)
  RETURNS tint
  AS 'MODULE_PATHNAME', 'Temporal_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(tfloat)
  RETURNS tfloat
  AS 'MODULE_PATHNAME', 'Temporal_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION arrowRoundtrip(ttext)
  RETURNS ttext
  AS 'MODULE_PATHNAME', 'Temporal_arrow_roundtrip'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

